
import React from "react";
import MainLayout from "@/components/MainLayout";

const Terms = () => {
  return (
    <MainLayout>
      <div className="container mx-auto px-4 py-12">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-3xl font-bold mb-6">Terms and Conditions</h1>
          
          <div className="prose dark:prose-invert max-w-none">
            <h2>1. Introduction</h2>
            <p>Welcome to GDPR Cookie Consent Generator ("we," "our," or "us"). By using our website, you agree to comply with and be bound by the following terms and conditions. Please review them carefully.</p>
            
            <h2>2. Acceptance of Terms</h2>
            <p>By accessing or using the GDPR Cookie Consent Generator, you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions. If you do not agree to these terms, please do not use our service.</p>
            
            <h2>3. Service Description</h2>
            <p>The GDPR Cookie Consent Generator provides a tool for creating GDPR-compliant cookie consent banners. The code generated is provided as-is, and we make no guarantees regarding its legal compliance in all jurisdictions. Users are responsible for ensuring their websites comply with all applicable laws and regulations.</p>
            
            <h2>4. User Responsibilities</h2>
            <p>When using our service, you agree to:</p>
            <ul>
              <li>Provide accurate information when customizing your cookie consent banner</li>
              <li>Use the generated code in compliance with applicable laws</li>
              <li>Not use our service for any illegal purpose</li>
              <li>Not attempt to interfere with or disrupt the service</li>
            </ul>
            
            <h2>5. Intellectual Property</h2>
            <p>The GDPR Cookie Consent Generator, including its content, features, and functionality, is owned by us and is protected by copyright, trademark, and other intellectual property laws. The code generated by our tool is provided for your use, but we retain ownership of the tool itself.</p>
            
            <h2>6. Generated Code Usage</h2>
            <p>You are granted a non-exclusive, worldwide license to use, copy, and implement the code generated by our tool on websites you own or manage. You may modify the generated code to suit your needs.</p>
            
            <h2>7. No Warranty</h2>
            <p>THE GDPR COOKIE CONSENT GENERATOR IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.</p>
            
            <h2>8. Limitation of Liability</h2>
            <p>IN NO EVENT SHALL WE BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA, OR OTHER INTANGIBLE LOSSES RESULTING FROM THE USE OF OR INABILITY TO USE THE SERVICE.</p>
            
            <h2>9. Third-Party Links</h2>
            <p>Our website may contain links to third-party websites or services that are not owned or controlled by us. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party websites or services.</p>
            
            <h2>10. Changes to Terms</h2>
            <p>We reserve the right to modify these terms at any time. We will provide notice of significant changes by posting the new terms on our website. Your continued use of the service after such modifications constitutes your acceptance of the revised terms.</p>
            
            <h2>11. Governing Law</h2>
            <p>These Terms shall be governed by and construed in accordance with the laws, without regard to its conflict of law provisions.</p>
            
            <h2>12. Contact Information</h2>
            <p>If you have any questions about these Terms, please contact us.</p>
            
            <p className="text-sm text-gray-500 mt-8">Last updated: April 7, 2025</p>
          </div>
        </div>
      </div>
    </MainLayout>
  );
};

export default Terms;
